[package]
name = "hull-white"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
ndarray = "0.15"
ndarray-csv = "0.5.2"
plotpy = "1.7.1"
plotters = "0.3"
rand = "0.8.5"
rand_distr = "0.4.3"
